font_family      MesloLGS NF
bold_font        MesloLGS NF Bold
italic_font      MesloLGS NF Italic
bold_italic_font MesloLGS NF Bold Italic
font_size        15.0
cursor_shape     block
hide_window_decorations no
background_opacity 0.9

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
